version: '3.8'

services:
  web:
    restart: unless-stopped
    build: .
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # xexbo
      - "traefik.http.routers.web.rule=Host(`xexbo.com`) || Host(`mm.xexbo.com`) || Host(`hub.xexbo.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.middlewares.web.redirectscheme.scheme=https"
      - "traefik.http.middlewares.web.redirectscheme.permanent=true"
    depends_on:
      - traefik

  # Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=hvalick2111@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/letsencrypt:/letsencrypt"
    networks:
      - web

networks:
  web:
    name: web
    attachable: true